### ISSUE TITLE
Update new board URL

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/DAPLink#4]
## Depends on

None.

## Description

Need to sync with web team to create a new landing page for the board/target URL embedded in DAPLink and submit a patch upstream with the new URL.

## Todo

* [x] Check that web task is completed
* [x] Update URL in our fork and test
* [x] Send PR to upstreams DAPLink
* [x] Follow up PR, respond/implement review comments and collaborate until merge

## Completion Criteria

* [x] Website landing page (even if it is a redirect)
* [x] New URL in DAPLink master for micro:bit builds

## Conclusion

Implemented in PR ARMmbed/DAPLink#464 merged to master.
Released in DAPLink v0247: https://github.com/ARMmbed/DAPLink/releases/tag/v0247

**Comment by microbit-carlos** [comment]
https://github.com/microbit-foundation/microbit-i18n/issues/852

**Comment by microbit-carlos** [comment]
https://github.com/microbit-foundation/microbit-i18n/issues/852

**Comment by microbit-carlos** [comment]
Waiting for the URL to be live before closing this one.

**Comment by microbit-carlos** [comment]
Landing page redirect done in https://github.com/microbit-foundation/microbit-i18n/pull/960.
