### ISSUE TITLE
Add target URL to details.txt file 

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/DAPLink#5]
## Depends on

Nothing

## Description

It is useful for editors to be able to grab the URL and direct users there in some situations.
Grabbing the URL from the HTML file would require funny and brittle implementations (possibly with regexes), this should be easily available in the details.txt file, where it belongs together with other useful board information. 

## Todo

* [x] Implement in fork
    - https://github.com/microbit-foundation/DAPLink/tree/details_url
* [x] Submit PR
* [x] Follow up PR, respond/implement review comments and collaborate until merge

## Completion Criteria

- [x] Changes merged upstream

## Conclusion

Implemented by Mbed team.
Released in DAPLink v0247: https://github.com/ARMmbed/DAPLink/releases/tag/v0247

**Comment by microbit-carlos** [comment]
https://github.com/microbit-foundation/DAPLink/tree/details_url

**Comment by microbit-carlos** [comment]
Implemented by the Mbed team and in master already.
